# Generated by Django 3.2.3 on 2021-05-17 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendor', '0001_initial'),
        ('dish', '0002_alter_dishdetails_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishdetails',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendor.restaurant'),
        ),
    ]
