# Generated by Django 3.2.3 on 2021-05-15 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dish', '0002_alter_dishdetails_restaurant'),
        ('orders', '0003_auto_20210515_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dish.dishdetails'),
        ),
    ]
