# Generated by Django 3.2.3 on 2021-05-16 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_orderitem_staus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='staus',
            new_name='status',
        ),
    ]
